### ISSUE TITLE
Forex not refreshing

### ISSUE THREAD

**Issue by sastools** [sthocs/firestocks#3]
It appears the API you use for Forex / Crypto has also been deprecated.

But, I was playing around with the financialmodelingprep API and it appears you can get this same info.
They have blocked the most obvious API calls .. 
https://financialmodelingprep.com/api/v4/forex/last/EURUSD and
https://financialmodelingprep.com/api/v4/crypto/last/BTCUSD

But some other API are available for free ..
For Forex, you have
https://financialmodelingprep.com/api/v3/fx/EURUSD

but you can still use the following with the free API for "Intraday Crypto"
https://financialmodelingprep.com/api/v3/historical-chart/4hour/BTCUSD?timeframe=4hour&from=2024-10-11&to=2024-10-11
and in the JSON results, if you open the first node, you will see the latest results
as long as the from and to parameters are the current date.

**Comment by sthocs** [comment]
Sorry for answering only now.
Thanks for the pointers, it seems the API indeed got enriched since I first explored it :)
When trying a few calls, I actually found out that the `quote` endpoint now works with Forex and Crypto too 🙌 

- https://site.financialmodelingprep.com/developer/docs/full-quote-forex
- https://site.financialmodelingprep.com/developer/docs/bitcoin-price-free-api

I'll update the plugin to rely solely on the FMP `quote` endpoint.

**Comment by sthocs** [comment]
Done in ff22569c6c2fd506a52c0640c0947414bafd72c5, let me know if you see problems!
